### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by giampaolo** [basak/ddar#11]
I remember I used this great tool something like 4-5 years ago and it worked great back then, but now that I look at it it seems it hasn't been updated in a while. 
As of today, would it make sense to use ddar in production?

**Comment by basak** [comment]
I'd say the project is done, rather than abandoned. It continues to work as intended. There is scope for further features but I don't currently have an interest in extending it.

I know of production ddar use, but I don't know of any issues. So for production I'd say its fine if you can sort out deployment (I never got round to packaging ddar for Debian).
