### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by alexreg** [basak/ddar#6]
More specifically, I'm wondering (a) if you've thought about integrating the patch for Mac OS X support from https://github.com/basak/ddar/pull/5 (b) tagging any releases? Indeed, (b) would allow me to write a Mac Homebrew formula for the software.

Any updates would be appreciated.

**Comment by basak** [comment]
Yes, but it's feature complete for me for now, so only in (slow) maintenance mode right now.

I just commented on #5. I'd be happy to tag a release, and appreciate you considering Homebrew for me. I could do that now, but would it be easier to resolve #5 first?

Could you try merging my experimental/portable2 branch for me, and if that works, I can merge and tag a release?

I'll close this issue, since the answer is "yes, it is".

**Comment by alexreg** [comment]
@basak Thanks for the response. That sounds fair; I've no reason to think it's anything but stable right now. Of course, it doesn't build nicely on OS X as we know, so that would be the one thing to rectify before making an official release, as you say.

I'll gladly test out the latest revision with experimental/portable2 merged in, and report back. Shall I create a new pull request when ready?

**Comment by alexreg** [comment]
Incidentally, what's with the `Makefile.prep`? I just ran `make -f Makefile.prep pydist`, but was curious...

**Comment by alexreg** [comment]
Okay, so it seems to compile and run fine for me! Haven't tested anything much though.

**Comment by basak** [comment]
No need for a pull request - just let me know whichever way you like. Does your compiling including merging experimental/portable2, ie. do you think that I am OK to merge it and tag a version 1.0?

> Incidentally, what's with the Makefile.prep? I just ran make -f Makefile.prep pydist, but was curious...

A Python sdist is "derived" from this git source, and includes the need to generate the manpage and the protobuf pieces (which, annoyingly, require generation of Python source, rather than doing it dynamically).

**Comment by alexreg** [comment]
Indeed, experimental/portable2 merged into master with no problems. Feel free to do that yourself and tag the release now.

Okay, that kind of makes sense regarding the Python sdist, though I'm still not sure while the file is called Makefile.prep and not Makefile. Not to worry though.

Anyway, thanks for all your good work on ddar; I'm looking forward to adding it to Homebrew soon.

**Comment by basak** [comment]
I've tagged v1.0. Thank you for looking at Homebrew for me! Please let me know if you need anything else.

**Comment by alexreg** [comment]
Thanks! That should be good for now, though I will do.

**Comment by alexreg** [comment]
Hi @basak, just to let you know that ddar is now officially a package on Mac Homebrew: https://github.com/Homebrew/homebrew/commit/501af0eedb0d01b11f4726274d0069af341aa2f8

Hopefully the one-line install command will now encourage more people to use this great little utility, at least on Mac.

**Comment by basak** [comment]
Wow, thanks! I'll gladly accept any pull request for README.markdown if you want to put any instructions there.

**Comment by alexreg** [comment]
@basak Certainly I could do that. Maybe you'd like to put Ubuntu/Debian instructions in the README first though, explicitly (in addition to the link perhaps)? If you put in an APT command line (or whatever the package manager for Ubuntu & Debian is these days) then I could do something similar for Brew.
